packages:
  - packages-app/*

catalog:
  '@tailwindcss/postcss': ^4
  '@types/node': ^20
  '@types/react': ^19
  '@types/react-dom': ^19
  babel-plugin-react-compiler: 1.0.0
  next: 16.0.10
  react: 19.2.1
  react-dom: 19.2.1
  tailwindcss: ^4
  typescript: ^5

onlyBuiltDependencies:
  - sharp
