packages:
  - packages-app/*
onlyBuiltDependencies:
  - sharp
catalog:
  "@mt-kit/cli-run": ^1.0.0
  "@mt-kit/eslint-config": ^2.4.2
  "@mt-kit/prettier-config": ^1.2.2
  "@mt-kit/stylelint-config": ^2.1.1
  "@mt-kit/ts-config": ^1.3.0
  "@tailwindcss/postcss": ^4
  "@types/node": 20.19.26
  "@types/react": ^19
  "@types/react-dom": ^19
  babel-plugin-react-compiler: 1.0.0
  eslint: ^9.39.1
  next: 16.0.10
  prettier: ^3.7.4
  react: 19.2.1
  react-dom: 19.2.1
  stylelint: ^16.26.1
  tailwindcss: ^4
  typescript: 5.9.3
